plugins {
	id 'java'
	id 'org.springframework.boot' version '4.1.1'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
}

//dependencies {
//
//// gateway 의존성 추가
//	implementation 'org.springframework.cloud:spring-cloud-starter-gateway'
//
//// eureka client 의존성 추가 => API Gateway가 eureka에게 마이크로서비스의 위치를 질의해야 하므로
//// netflix => 넷플릭스에서 수많은 영상서비스를 제공하다보니 최초로 spring cloud 관련한 서비스를 개발해낸 라이브러리들이 많음
////            이 라이브러리들에 netflix 키워드를 붙여 개발한 후 이것을 오픈소스로 공개함
//
//	implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'
//
////	jwt토큰 관련 라이브러리 추가 => API Gateway에서 토큰 인증 처리를 하므로 필요
//	implementation 'io.jsonwebtoken:jjwt-api:0.11.5'
//	runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.11.5'
//	runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.11.5'  // JSON 처리에 필요
//}
//
//// springcloud 전체에 대한 버전 명시
//dependencyManagement {
//	imports{
//		mavenBom 'org.springframework.cloud:spring-cloud-dependencies:2025.1.2'
//	}
//}

dependencies {
	implementation 'org.springframework.cloud:spring-cloud-starter-gateway-server-webflux'
//	implementation 'org.springframework.cloud:spring-cloud-starter-gateway-server-webmvc'
	implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'

	implementation 'io.jsonwebtoken:jjwt-api:0.11.5'
	runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.11.5'
	runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.11.5'
}

dependencyManagement {
	imports {
		mavenBom 'org.springframework.cloud:spring-cloud-dependencies:2025.1.2'
	}
}

tasks.named('test') {
	useJUnitPlatform()
}
